### ISSUE TITLE
2023 preparations todo list

### ISSUE THREAD

**Issue by DaanVanHauwermeiren** [DaanVanHauwermeiren/AdventofCode#5]
# script for solution checking
- [x] setup environments:
    - [X] python
    - [x] julia
- [x] load the previously stored timings of the solutions: df_exectime
- [x] read in filenames of all solution in ./code
- [x] check filenames with entries in df_exectime: make list of files that are new and need to be run 
- [x] depending on extension: choose the correct way to run this.
    - [x] first assert that code is correct and returns the correct solution
    - [ ] define some standardised timing scheme to run it, e.g. 10x or so
- [x] add timing to df_exectime
- [ ] ~julia: Pipe.jl or Underscores.jl~
- [ ] add something for least amount of bytes (skipping comments)
- [x] some solutions are string: should I use string everywhere?

# others
- [x] add badge
- [x] add gitter
- [ ] add precommit
- [ ] add CI
- [x] update contributing
- [x] muck out utitlities
- [x] add logo
